taoweb/taoweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from BlogDemo.views import IndexView,register,login,article_detail,article_publish,ArticleDetailView,likes_add,retrievepasswd,logout,CommentDetailView,comment_commit,comment_reply,article_search
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	path('',IndexView.as_view(template_name="index.html"),name='home_page') ,
	url(r'^home/',IndexView.as_view(template_name="index.html"),name='home_page') ,
	url(r'^login/',login,name='login_page') ,
	url(r'^logout/',logout,name='logout_page') ,
	url(r'^retrievepasswd/',retrievepasswd,name='retrievepasswd_page') ,
	url(r'^article/(?P<article_id>\d+)/likes',likes_add,name='likes_add_page') ,
	url(r'^register/',register,name='register_page') ,
	url(r'^comment_commit/(?P<article_id>\d+)',comment_commit,name='comment_commit_page'),
	url(r'^comment_reply/(?P<article_id>\d+)',comment_reply,name='comment_reply_page'),
	url(r'^article/(?P<article_id>\d+)',ArticleDetailView.as_view(),name='article_detail_page'),
	url(r'^comment/(?P<comment_id>\d+)',CommentDetailView.as_view(),name='comment_detail_page'),
	url(r'^category/(?P<cate_id>\d+)',IndexView.as_view(template_name="category_list.html"),name='category_article_page'),
	url(r'^article_create/',IndexView.as_view(template_name="article_create.html"),name='article_create_page'),
	url(r'^article_publish/',article_publish,name='article_publish_page'),
	url(r'^article_search/', article_search,name='article_search_page'),







]

taoweb/BlogDemo/models.py
#encoding=utf-8
from django.db import models
from  django.urls import reverse

# Create your models here.
class Article(models.Model):
	status_choice=(
		('d','draft'),
		('p','Published')
	)
	
	title = models.CharField(u'标题',max_length=70)
	body = models.TextField(u'正文')
	create_time = models.DateTimeField(u'创建时间',auto_now_add=True)
	last_modified_time = models.DateTimeField(u'最后修改时间',auto_now = True)
	status = models.CharField(u'文章状态',max_length=1,choices = status_choice)
	abstract = models.CharField(u'文章摘要',max_length=54,blank=True,null=True,help_text=u'可选，如若为空将摘取正文的前54个字符')
	views = models.PositiveIntegerField(u'浏览量',default=0)
	likes = models.PositiveIntegerField(u'点赞数',default=0)
	likes_user = models.ManyToManyField('User',verbose_name=u'点赞人',null=True,related_name='user_hit_likes')
	topped = models.BooleanField(u'置顶',default=False)
	auther = models.ForeignKey('User',verbose_name = u'作者',null=True,on_delete = models.SET_NULL)
	category = models.ForeignKey('Category',verbose_name=u'分类',null=True,on_delete = models.SET_NULL)
	
	def __str__(self):
		return self.title
		
	def __unicode__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse('article_detail_page',kwargs={'article_id': self.pk})
		
	class Meta:
		ordering = ['-last_modified_time']

class Comment(models.Model):
	status_choice=(
		('R',u'已读'),
		('N',u'未读')
	)
	comment_user = models.ForeignKey('User',verbose_name = u'评论人',related_name="comment_user",on_delete=models.CASCADE)
	comment_content = models.TextField(u'评论内容')
	comment_status = models.CharField(u'评论状态',max_length=10,choices = status_choice,default=u"未读")
	comment_time = models.DateTimeField(u'评论时间',auto_now = True)
	comment_reminder = models.ForeignKey('User',verbose_name=u"提醒人",null=True,related_name="comment_reminder",on_delete=models.CASCADE)
	article = models.ForeignKey('Article',verbose_name = u'归属文章',on_delete=models.CASCADE)
	
	def __str__(self):
		return self.comment_user.name
	
	def __unicode__(self):
		return self.comment_user.name
		
	class Meta():
		ordering = ['comment_time']
		
class Category(models.Model):
	name = models.CharField(u'类名',max_length=20)
	create_time = models.DateTimeField(u'创建时间',auto_now_add=True)
	last_modified_time = models.DateTimeField(u'最后修改时间',auto_now = True)
	
	def __str__(self):
		return self.name
		
	def __unicode__(self):
		return self.name
	
	class Meta():
		ordering = ['-last_modified_time']
		
class User(models.Model):
	user_status=(
		('invisible',u'隐身'),
		('online',u'在线'),
		('offline',u'离线')
	)
	name = models.CharField(u'用户名',max_length=20)
	passwd = models.CharField(u'密码',max_length=20,null = True)
	email = models.EmailField(u'邮箱地址',max_length=256,default='huwt15@163.com')
	status = models.CharField(u'状态',max_length=10,choices = user_status,default='online')
	last_login_time = models.DateTimeField(u'最后一次登录时间',auto_now = True)
	
	def __str__(self):
		return self.name
	
	def __unicode__(self):
		return self.name
		
	class Meta():
		ordering = ['last_login_time']

taoweb/BlogDemo/views.py
#encoding=utf-8
from django.shortcuts import render,HttpResponseRedirect,get_object_or_404
from BlogDemo.models import *
from django.views.generic import ListView,DetailView
from django.contrib import auth
from django.core.mail import send_mail,EmailMultiAlternatives
from django.conf import settings
import markdown2
import jieba

# Create your views here.
class IndexView(ListView):
	context_object_name = "article_list"
	template_name = "index.html"
	
	def get_queryset(self):
		self.request.session["current_url"] = self.request.path#获取当前页面url存入session中，如果文章只是刷新页面,而页面不跳转，则阅读数不增加。
		if self.template_name == "category_list.html":
			article_list=Article.objects.filter(category=self.kwargs['cate_id'],status='p')#如果传入category_id则获取对应分类文章作为article_list
		else:
			article_list = Article.objects.filter(status = 'p')#如果不传入category_id则获取所有文章作为article_list
		for articles in article_list:
			articles.body = markdown2.markdown(articles.body)#文章body部分进行markdown渲染
		return article_list
	
	def get_context_data(self,**kwargs):
		new_comment_list = []
		try:
			kwargs['category_name']=Category.objects.get(id=self.kwargs['cate_id']).name
		except:
			pass
		try:
			user_name = self.request.session['username']
			user = get_object_or_404(User,name=user_name)
			new_comment_list = Comment.objects.filter(comment_reminder=user,comment_status="N")
		except 	KeyError:
			pass
		comment_count = len(new_comment_list)
		kwargs['comment_list_user'] = new_comment_list
		kwargs['comment_count_user'] = comment_count
		kwargs['latest_login_user']=User.objects.all().order_by('-last_login_time')[:5]
		kwargs['category_list']=Category.objects.all().order_by('name')
		kwargs['popular_article']=Article.objects.all().order_by('likes')[:5]
		kwargs['views_article']=Article.objects.all().order_by('-views')[:5]
		kwargs['user_count']=User.objects.all().count()
		kwargs['article_count']=Article.objects.all().count()
		return super(IndexView,self).get_context_data(**kwargs)
		
def login(request):
	try:
		name,password,email = request.session['user_name_create'],request.session['password'],request.session['email']
		User.objects.create(name=name,passwd=password,email = email)
		del request.session['user_name_create'],request.session['password'],request.session['email']
		return render(request,"login.html",{'login_err':u'用户注册成功，请登录'})
	except:
		pass
	if request.method == "POST":
		username = request.POST.get("username")
		password = request.POST.get("password")
		new_comment_list = []
		try:
			user = User.objects.get(name=username,passwd=password)
			new_comment_list = Comment.objects.filter(comment_reminder=user,comment_status="N")
		except :
			return render(request,'404.html')
		article_list = Article.objects.filter(status = 'p')
		for articles in article_list:
			articles.body = markdown2.markdown(articles.body,)
		category_list = Category.objects.all().order_by('name')
		popular_article = Article.objects.all().order_by('-likes')[:5]
		views_article = Article.objects.all().order_by('views')[:5]
		user_count = User.objects.all().count()
		article_count = Article.objects.all().count()
		latest_login_user = User.objects.all().order_by('-last_login_time')[:5]
		
		comment_count_user = len(new_comment_list)
		if user:
			request.session["current_url"] = request.path
			request.session['username'],request.session['password'] = username,password
			return render(request,"index.html",{"comment_list_user":new_comment_list,"comment_count_user":comment_count_user,\
			"latest_login_user":latest_login_user,"user_count":user_count,"article_count":article_count,"article_list":article_list,\
			"category_list":category_list,"popular_article":popular_article,"views_article":views_article})
		else:
			return render(request,"login.html",{'login_err':u'用户名或密码错误'})
	else:
		return render(request,"login.html")
	
def register(request):
	error_info = ""
	user = ""
	user_email= ""
	if request.method == "POST":
		name = request.POST.get("username")
		email = request.POST.get("email")
		password = request.POST.get("password")
		repetpassword = request.POST.get("repeat_password")
		from_email = settings.DEFAULT_FROM_EMAIL
		try:
			user = User.objects.get(name=name)
		except:
			pass
		try:
			user_email = User.objects.get(email=email)
		except:
			pass
		if password != repetpassword:
			error_info = u'两次输入密码不一致，请检查后重新输入'
		elif user:
			error_info = u'当前用户已经存在，请更换账号重新注册'
		elif user_email:
			error_info = u'当前邮箱已经被占用，请更换邮箱重新注册'
		else:
			request.session['user_name_create'],request.session['password'],request.session['email'] = name,password,email
			url = 'http://127.0.0.1:8000/login/'
			subject = '欢迎加入hwt，请验证登录邮箱'
			text_content = u'欢迎加入hwtweb，您的登录邮箱是:'+email+'\n'+\
			u'请点击以下链接验证你的邮箱地址，以便以后找回账户信息'+'\n\n'+url+'\n'+\
			u'如果以上链接无法访问，请将该网址复制并粘贴到浏览器窗口进行访问'
			msg = EmailMultiAlternatives(subject, text_content, from_email, [email])
			msg.send()
			error_info = u'邮箱验证邮件已经发送到您的邮箱,请按照提示完成相关验证'
		return render(request,"register.html",{'error_info':error_info})
	return render(request,"register.html",{'error_info':error_info})
	
def logout(request):
	if request.user:
		auth.logout(request)
		request.user = ""
	return render(request,'login.html',{'login_err':u'注销成功'})
	
def retrievepasswd(request):
	category_list = Category.objects.all().order_by('name')
	popular_article = Article.objects.all().order_by('-likes')[:5]
	views_article = Article.objects.all().order_by('views')[:5]
	user_count = User.objects.all().count()
	article_count = Article.objects.all().count()
	latest_login_user = User.objects.all().order_by('-last_login_time')[:5]
	
	if request.method == "POST":
		To_email = request.POST.get('email')
		username = request.POST.get('username')
		from_email = settings.DEFAULT_FROM_EMAIL
		try:
			user = User.objects.get(name=username,email = To_email)
			subject = '申请获取taoweb账户信息邮件'
			text_content = u'#重新获取账号信息:'+'\n\n'+u'您的账号为:'+user.name+'\n\n'+u'账号密码为:'+user.passwd
			msg = EmailMultiAlternatives(subject, text_content, from_email, [To_email])
			msg.send()
			return render(request,"login.html",{'login_err':u'账户信息已经发送至您的邮箱，请查收'})
		except:
			return render(request,"reset_passwd.html",{'error_msg':u'您的邮箱信息与账号不匹配,请重新填写'})

	return render(request,"reset_passwd.html",{'category_list':category_list,'popular_article':popular_article,'views_article':views_article,'user_count':user_count,'article_count':article_count,'latest_login_user':latest_login_user})
	
def article_search(request):
	new_comment_list = []
	article_list = []
	keywords = request.GET.get('search_key')
	for article in Article.objects.all():
		title_data = ';'.join(jieba.cut(article.title,cut_all=True))
		title_data_list = title_data.split(';')
		content_data = ';'.join(jieba.cut(article.body,cut_all=True))
		content_data_list = content_data.split(';')
		if keywords in content_data_list or keywords in title_data_list:
			article_list.append(article)
	try:
		user_name = request.session["username"]
		user = User.objects.get(name = user_name)
		new_comment_list = Comment.objects.filter(comment_reminder=user,comment_status="N")
	except:
		pass
	comment_count_user = len(new_comment_list)
	category_list = Category.objects.all().order_by('name')
	popular_article = Article.objects.all().order_by('-likes')[:5]
	views_article = Article.objects.all().order_by('views')[:5]
	user_count = User.objects.all().count()
	article_count = Article.objects.all().count()
	latest_login_user = User.objects.all().order_by('-last_login_time')[:5]		
	return render(request,"search_list.html",{"comment_list_user":new_comment_list,"comment_count_user":comment_count_user,\
			"latest_login_user":latest_login_user,"user_count":user_count,"article_count":article_count,\
			"category_list":category_list,"popular_article":popular_article,"views_article":views_article,"article_list":article_list})	

def article_detail(request):
	return render(request,"article_detail.html")
	
def article_publish(request):
	if request.method == "POST":
		user_name = request.session['username']
		user = User.objects.get(name=user_name)
		article_title = request.POST.get("title")
		abstract = request.POST.get("abstract")
		article_body = request.POST.get("content")
		catogory_name = request.POST.get("category")
		category = Category.objects.get(name=catogory_name)
		article_status = request.POST.get("status")
		article_body = markdown2.markdown(article_body)
		Article.objects.create(title=article_title,body=article_body,status=article_status,abstract=abstract,auther=user,category=category)
	
	article_list = Article.objects.filter(status = 'p')
	for articles in article_list:
			articles.body = markdown2.markdown(articles.body,)
	user_count = User.objects.all().count()
	article_count = Article.objects.all().count()
	latest_login_user = User.objects.all().order_by('-last_login_time')[:5]
	category_list = Category.objects.all().order_by('name')
	popular_article = Article.objects.all().order_by('-likes')[:5]
	views_article = Article.objects.all().order_by('views')[:5]
	new_comment_list = []
	new_comment_list = Comment.objects.filter(comment_reminder=user,comment_status="N")
	comment_count_user = len(new_comment_list)
	return render(request,"index.html",{"comment_list_user":new_comment_list,"comment_count_user":comment_count_user,"latest_login_user":latest_login_user,"user_count":user_count,"article_count":article_count,"article_list":article_list,"category_list":category_list,"popular_article":popular_article,"views_article":views_article})
	
def comment_reply(request,article_id):
	user_name = request.session["username"]
	user_reply = User.objects.get(name=user_name)
	article = Article.objects.get(id = article_id)
	article_url = article.get_absolute_url()
	reply_content = request.POST.get('reply_content')
	replay_data_list = request.POST.get('reply_content').split(":")
	user_reminder_name = replay_data_list[0][1:]
	user_reminder = User.objects.get(name=user_reminder_name)
	comtent_without_user = replay_data_list[1]
	if comtent_without_user !="":

taoweb/BlogDemo/templates/article_detail.html
{%extends "top.html"%}
{%block page-content%}
    <!--网站中间部分内容开始-->
    <div id="wrap">
        <div class="container" id="main">
            <!--左边内容-->
            <div class="col-md-8" id="left">
                     <!--页面左边的内容-->
    <!--展示帖子相关内容的代码开始-->
    <div class="panel panel-default panel-amend">
        <div class="topic-heading panel-heading">
            <div class="row">
                <div class="col-md-10" id="limit-title-width">
                    <p class="topic-breadcrumb">
                        <a href="{% url 'category_article_page' article.category.pk %}">{{article.category.name}}</a>  ›   <a href="#">{{article.title}}</a>
                    </p>
				</div>
				<div class="col-md-8" id="left1">
                    <h4 class="list-post-title-in-topic">{{article.title}}</h4>
				</div>
				<div class="col-md-4" id="right1">
						<span class="list-username pull-right"><a href="#">作者:{{article.auther.name}}</a></span>
						<a href="http://www.aeflt.net/user/center/display/?uid=1" class="col-md-1 pull-right">
							<img class="avatar-middle pull-right" src="../static/7c93baa4-056c-11e6-8212-000c2919e245.jpg" title="admin">
						</a>
				</div>
				<div class="col-md-12" id="limit-title-width">
                    <p class="list-meta">
						{% if not in_likes_user %}
						{% if request.session.username	 %}
						<a href="{%url 'likes_add_page' article.pk%}"><span id = "likes_hit" class="badge list-reply-count hidden-xs">点赞{{article.likes_user.count}}</span></a>
						{% else%}
						<a href="#"><span id = "not_login" class="badge list-reply-count hidden-xs">点赞{{article.likes_user.count}}</span></a>
						{% endif %}
						{%else%}
						<a href="#"><span id = "likes_hitted" class="badge list-reply-count hidden-xs">点赞{{article.likes_user.count}}</span></a>
						{%endif%}
						<span class="label label-default list-meta-node"><a href="#">{{article.abstract}}</a></span>
					    <span class="list-count">浏览次数:{{article.views}}</span>
						<span class="list-time">{{article.create_time|date:"Y年m月d日"}}</span>
				    </p>
					
                </div>
				{% ifequal  article.likes_user.count 0 %}
				{%else%}
				<div class="col-md-12" id="limit-title-width">
					<span class="list-count">点赞{{article.likes_user.count}}人:{{users_likes}}</span>
				</div>
				{%endifequal%}
            </div>
        </div>
        <div class="panel-body">
            <p></p><p>
	<span style="font-size:16px;">{{article.body|safe}}</span>
</p>
<p>
	<span style="font-size:16px;"><br>
</span>
</p>
<p>
	<span style="font-size:16px;"><div class="social-share" data-sites="weibo,qq,qzone,tencent,douban"></div><br>
</span>
</p><p></p>
        </div>
    </div>
    <!--展示帖子相关内容的代码结束-->
    <!--展示评论代码开始-->
    <div class="panel panel-default panel-amend">
        <div class="panel-heading panel-heading-amend">
            <p class="panel-title">评论[{{comment_count}}]
			</p>
			
        </div>
       <ul class="list-group">
            
                {%for comments in comment_list%}
                    <div class="list-group-item list-topic-item">
                        <div class="row ">
                            <a href="#" class="col-md-1 col-xs-2 col-sm-2" id="limit-comment-width">
                                <img class="avatar-middle" src="../static/7c93baa4-056c-11e6-8212-000c2919e245.jpg" title="fiyahanxue">
                            </a>
                            <div class="col-xs-11">
                                <div class="row">
                                    <div class="reply-author col-sm-10">
                                        <a href="#" id="{{comments.comment_user}}">{{comments.comment_user}}</a>
                                        <span class="list-time">{{comments.comment_time|date:"Y-m-d H:m:i"}}</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8">
                                            <p>{{comments.comment_content|safe}}</p>
                                    </div>
									<div class="col-md-4 pull-right" id="right2">
                                            <p><label class="pull-right" title="{{comments.comment_user}}" onclick="showreplayform(this)"><a>回复</a></label>&nbsp&nbsp&nbsp&nbsp&nbsp</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {%endfor%}
                
            
        </ul>

    </div>
    <!--展示评论代码结束-->
    <!--发表评论代码开始-->
    <div class="panel panel-default panel-amend">
        {% if request.session.username %}
		<div class="panel-body" id="comment-form" style="display:block">
            <div class="row">
                
                    <form class="form-horizontal" method="post" action="{%url 'comment_commit_page' article.pk%}">
                        <div class="form-group ">
                            <label class="label-title">评论</label>
                            <div class="col-article">
                                <input type="text" class="form-control" name="comment" required="" value=""></input>
                            </div>
                        </div>
						<div class="form-group">
							<button type="submit" class="btn btn-success btn-create">发表</button>
						</div>
					</form>
			</div>
		</div>
		<div class="panel-body" id="replay-form" style="display:none">
            <div class="row">
                
                    <form class="form-horizontal" method="post" action="{%url 'comment_reply_page' article.pk%}">
                        <div class="form-group ">
                            <label class="label-title">回复</label>
                            <div class="col-article">
                                <input type="text" id="reply_input" class="form-control" name="reply_content" required=""></input>
                            </div>
                        </div>
						<div class="form-group">
							<button type="submit" class="btn btn-success btn-create">发表</button>
						</div>
					</form>
			</div>
		</div>
		{%else%}
        <div class="panel-body">
            <div class="row">
                
                    <span class="remind_info">
                        对不起！您还未登录！<a href="/login/">点此登录 </a>或者
                        <a href="/register/"> 点此注册</a>
                    </span>
                
            </div>
        </div>
		{%endif%}
    </div>
    <!--发表评论代码结束-->
 <!--定义字模板可以继承的左边的内容块-->
            </div>
            <!--右边内容-->
            <div class="col-md-4" id="right">
                 <!--页面右边的内容-->
    <!--引入版块切换的代码-->
    <div class="panel panel-default panel-amend">
    <div class="panel-heading panel-heading-amend">
        <h3 class="panel-title">文章分类</h3>
    </div>
    <div class="panel-body">
        {%for category in category_list%}
            <a class="btn btn-default category_btn" href="{% url 'category_article_page' category.pk %}">{{category.name}}</a>
        {%endfor%}
    </div>
</div>
    
    <!--引入精品帖子推荐排行的代码-->
    <div class="panel panel-default panel-amend">
    <div class="panel-heading panel-heading-amend">
        <h3 class="panel-title">最受欢迎文章</h3>
    </div>
    <ul class="list-group">
        
            <!--限制只在精华帖子面板处显示最新的10条精华帖子-->
            
                <li class="list-group-item">
					{%for articles in popular_article%}
                    <div class="row row_min_height">
                        <a href="#" class="recommend_topic"><img class="recommend_topic_img" src="../static/7c93baa4-056c-11e6-8212-000c2919e245.jpg" title="admin"></a>
						<div class="recommend_topic_list">
                            <a href="{%url 'article_detail_page' articles.pk%}" title="{{articles.title}}">{{articles.title}}</a>
                        </div>	
                    </div>
					{%endfor%}
                </li>
    </ul>
</div>
    <!--引入浏览量排行代码-->
    <div class="panel panel-default panel-amend">
    <div class="panel-heading panel-heading-amend">
        <h3 class="panel-title">浏览量排行榜</h3>
    </div>
    <ul class="list-group">
        
            <li class="list-group-item">
			{%for articles in views_article%}
                <div class="row row_min_height">
                    <a href="http://www.aeflt.net/user/center/display/?uid=8" class="hot_topic"><img class="hot_topic_img" src="../static/default.jpg" title="潭州助理老师  瑾萱"></a>
                    <div class="hot_topic_list">
                        <a href="{%url 'article_detail_page' articles.pk%}" title="{{articles.title}}">{{articles.title}}</a>
                    </div>
                </div>
			{%endfor%}
            </li>
    </ul>
</div>
    <!--引入最近加入的用户代码-->
    <div class="panel panel-default panel-amend">
    <div class="panel-heading panel-heading-amend">
        <h3 class="panel-title">最近登录的用户</h3>
    </div>
    <div class="panel-body">
	{%for users in latest_login_user%}
		<span class="list-username">{{users.name}}</span>
	{%endfor%}
    </div>

</div>
    <!--引入论坛运行状态统计代码-->
    <div class="panel panel-default panel-amend">
    <div class="panel-heading panel-heading-amend">
        <h3 class="panel-title">论坛运行状态</h3>
    </div>
   <div class="list-group">
        <span class="list-group-item">当前用户总计:{{user_count}}</span>
		<span class="list-group-item">当前在线用户:{{user_count}}</span>
		<span class="list-group-item">当前文章总数:{{article_count}}</span>
    </div>
</div>

    <!--引入友情链接的代码-->
    <div class="panel panel-default panel-amend">
    <div class="panel-heading panel-heading-amend">
        <h3 class="panel-title">友情链接</h3>
    </div>
    <div class="panel-body">
        
            <a class="btn friendly_link" target="_blank" href="https://github.com/jimforit">Jim的GitHub首页</a>
        
            <a class="btn friendly_link" target="_blank" href="http://v3.bootcss.com/">Bootstrap文档</a>
        
            <a class="btn friendly_link" target="_blank" href="https://www.djangoproject.com/">Django官网</a>
        
    </div>
</div>
 <!--定义子模板可以继承的右边的内容块-->
            </div>
            <!--网站中间部分内容的左边内容结束-->
        </div>
    </div>
    <!--网站中间部分内容结束-->
 <!--定义子模板可以继承的网站中间部分的内容块-->
    <!--底部代码开始-->
    <footer class="footer-color nav-footer-color" id="footer">
        <div class="container clearfix">
            <div class="text-muted pull-left">
                   <p id="text-color">JimBlog</p>
            </div>
            <p class="muted credit pull-right" id="text-color">
                ©<time>2016</time> Powered by Jim
            </p>
        </div>
    </footer>
    <!--底部代码结束-->
    <script src="../static/jquery-2.1.1.min.js"></script>
    <script src="../static/bootstrap.min.js"></script>
	<script src="../static/dist/js/social-share.min.js"></script>
    <!--定义子模板可以继承的js块-->
	<script type="text/javascript">

$(function(){
		$("#likes_hit").click(function(e){
			anp(e);
		})
		$("#likes_hitted").click(function(e){
			anpped(e);
		})
		$("#not_login").click(function(e){
			not_login(e);
		})
	
});

function anp(e){
	var n=1;
	var $i=$("<b>").text("+"+n);
	var x=e.pageX,y=e.pageY;
	$i.css({top:y-20,left:x,position:"absolute",color:"#E94F06"});
	$("body").append($i);	
	$i.animate({top:y-180,opacity:0,"font-size":"1.4em"},1500,function(){
		$i.remove();
	});
	e.stopPropagation();
}
function anpped(e){
	var n='您已经点过赞，请勿重复点赞';
	var $i=$("<b>").text(n);
	var x=e.pageX,y=e.pageY;
	$i.css({top:y-20,left:x,position:"absolute",color:"#E94F06"});
	$("body").append($i);	
	$i.animate({top:y-180,opacity:0,"font-size":"1.4em"},1500,function(){
		$i.remove();
	});
	e.stopPropagation();
}
function not_login(e){
	var n='您尚未登录，无法点赞';
	var $i=$("<b>").text(n);
	var x=e.pageX,y=e.pageY;
	$i.css({top:y-20,left:x,position:"absolute",color:"#E94F06"});
	$("body").append($i);	
	$i.animate({top:y-180,opacity:0,"font-size":"1.4em"},1500,function(){
		$i.remove();
	});
	e.stopPropagation();
}
function showreplayform(id){
        var obj = document.getElementById("replay-form");
        obj.style.display = "block";
		window.location.href = "#replay-form";
		var comment_obj = document.getElementById("comment-form");
		comment_obj.style.display = "none";
		var comment_user = id.title
		document.getElementById("reply_input").value ="@"+comment_user+":";
		
}
</script>

<!--定义子模板可以继承的js块-->
{%endblock%}

taoweb/BlogDemo/templates/pagination.html
<div id="pagenavi" class="noselect" align="center">
    {% if article_list.has_previous %}
        <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    {% if first_page == current_page %}
        <span class="first-page current"></span>
    {% else %}
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %}
        <span>...</span>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <span class="current">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    {% if article_list.has_next %}
        <a class="next-page" href="?page={{ article_list.next_page_number }}">
            下一页<span class="icon-next"></span>
        </a>
    {% endif %}
</div>